language: python

sudo: false

env:
  - TOX_ENV=flake8
  - TOX_ENV=py37-latest
  - TOX_ENV=py38-latest
  # Django 2.2
  - TOX_ENV=py37-dj22-cms35
  - TOX_ENV=py37-dj22-cms36
  - TOX_ENV=py37-dj22-cms37
  - TOX_ENV=py37-dj22-cms38
  - TOX_ENV=py37-dj22-cms39
  - TOX_ENV=py38-dj22-cms35
  - TOX_ENV=py38-dj22-cms36
  - TOX_ENV=py38-dj22-cms37
  - TOX_ENV=py38-dj22-cms38
  - TOX_ENV=py38-dj22-cms39


install:
  - pip install tox coverage

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
